vérification recette avec tflint via la Gitlab CI (Test pipeline - syntaxe pour controle - 2)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,15 +13,12 @@ validate:
 
   before_script:
       - |
-      #!/bin/sh
-      fmt_diff=$(find . -name "*.tf" | xargs -I{} /terraform fmt -write=false {} | sed '/^\s*$/d')
-      if test -n "$fmt_diff"; then
-        echo "******* Terraform formatting error:"
-        echo ""
-        echo $fmt_diff
-        exit 1
-      fi
-
+        fmt_diff=$(find . -name "*.tf" | xargs -I{} /terraform fmt -write=false {} | sed '/^\s*$/d')
+        if test -n "$fmt_diff"; then
+          echo "******* Terraform formatting error:"
+          echo ""
+          echo $fmt_diff
+          exit 1
 
   script:
       - echo "Terraform Init !"
